function cursor_struct = cursor()
    app = Program.app;

    cursor_struct = struct( ...
        't', {round(app.tSlider.Value)}, ...
        'x', {round(app.video_info.ny - app.ySlider.Value)}, ...
        'y', {round(app.xSlider.Value)}, ...
        'z', {round(app.hor_zSlider.Value)}, ...
        'marker_size', {app.MarkerSizeSlider.Value});
end

