function addOpticalChannelFunction(app)
    % addOpticalChannelFunction - Handles adding an optical channel
    %
    % Inputs:
    %   app - The App Designer app object (to access the UI components for the optical channel details)
    
    % Create the optical channel structure from the UI input fields
    channel = struct( ...
        'fluorophore', char(app.FluorophoreEditField.Value), ...
        'filter', char(app.FilterEditField.Value), ...
        'excitation_lambda', char(num2str(app.ExLambdaEditField.Value)), ...
        'excitation_filter_low', char(num2str(app.ExFilterLowEditField.Value)), ...
        'excitation_filter_high', char(num2str(app.ExFilterHighEditField.Value)), ...
        'emmission_lambda', char(num2str(app.EmLambdaEditField.Value)), ...
        'emmission_filter_low', char(num2str(app.EmFilterLowEditField.Value)), ...
        'emmission_filter_high', char(num2str(app.EmFilterHighEditField.Value)));

    % Call the channel handler for the 'add' action
    Program.GUIHandling.channel_handler(app, 'add', channel);
end
