function local_roi_panel(state)
    app = Program.app;
    states = {'on', 'off'};
    c_components = {'NeuronnotrepresentedincurrentframeLabel'};
    components = { ...
        'XCoordinateEditField', ...
        'YCoordinateEditField', ...
        'ZCoordinateEditField', ...
        'AnnotationIDEditField', ...
        'XCoordinateLabel', ...
        'YCoordinateLabel', ...
        'ZCoordinateLabel', ...
        'AnnotationIDLabel', ...
        'Button_5', ...
        'Button_8'};

    if nargin == 0
        state = state{~ismember(states, app.(components{1}).Visible)};
    end

    c_state = states{~ismember(states, state)};

    for c=1:length(components)
        app.(components{c}).Visible = state;
    end

    for c=1:length(c_components)
        app.(c_components{c}).Visible = c_state;
    end
end

