function package = get_display_volume(app, target, raw_volume)
% Build a canonical display volume package for the requested UI target.

if nargin < 1 || isempty(app)
    app = Program.app;
end
if nargin < 2 || strlength(string(target)) == 0
    target = "main";
end
if nargin < 3
    raw_volume = [];
end

target = lower(string(target));

switch target
    case "main"
        if isempty(raw_volume)
            raw_volume = app.image_data;
        end
        state = Program.Handlers.channels.main_state(app);
        channels = struct( ...
            'r', state.r, ...
            'g', state.g, ...
            'b', state.b, ...
            'white', state.white, ...
            'dic', state.dic, ...
            'gfp', state.gfp, ...
            'other', {{}});
        threshold_raw = 0;
        if isstruct(app.image_prefs) && isfield(app.image_prefs, 'is_Z_flip')
            is_z_flip = app.image_prefs.is_Z_flip;
        else
            is_z_flip = false;
        end

    case "processing"
        if isempty(raw_volume)
            raw = Program.GUIHandling.get_active_volume(app, 'request', 'all');
            raw_volume = raw.array;
        end
        state = Program.Handlers.channels.processing_state(app);
        channels = struct( ...
            'r', Program.Handlers.channels.render_struct_from_row(state.r), ...
            'g', Program.Handlers.channels.render_struct_from_row(state.g), ...
            'b', Program.Handlers.channels.render_struct_from_row(state.b), ...
            'white', Program.Handlers.channels.render_struct_from_row(state.white), ...
            'dic', Program.Handlers.channels.render_struct_from_row(state.dic), ...
            'gfp', Program.Handlers.channels.render_struct_from_row(state.gfp), ...
            'other', {cellfun(@Program.Handlers.channels.other_struct_from_row, ...
                num2cell(state.other), 'UniformOutput', false)});
        threshold_raw = 0;
        is_z_flip = false;

    otherwise
        error('Unknown display target: %s', target);
end

[display_volume, rgb_channels] = Program.Helpers.compose_display_volume(raw_volume, channels);
display_volume = Program.Helpers.finalize_display_volume(display_volume, rgb_channels, threshold_raw);

package = struct( ...
    'target', char(target), ...
    'raw_volume', raw_volume, ...
    'channels', channels, ...
    'rgb_channels', {rgb_channels}, ...
    'threshold_raw', threshold_raw, ...
    'is_z_flip', logical(is_z_flip), ...
    'display_volume', display_volume);
end
