function initialize()
    app = Program.GUI.app;

    app.flags = struct();
    app.rotation_stack.cache = struct( ...
        'Colormap', {{}}, ...
        'Video', {{}});
            
    app.nameMap = containers.Map( ...
        {app.ProcRDropDown.Value, app.ProcGDropDown.Value, app.ProcBDropDown.Value, ...
         app.ProcWDropDown.Value, app.ProcDICDropDown.Value, app.ProcGFPDropDown.Value}, ...
        {'Red', 'Green', 'Blue', 'White', 'DIC', 'GFP'} ...
    );
    
    app.shortMap = containers.Map( ...
        {app.ProcRDropDown.Value, app.ProcGDropDown.Value, app.ProcBDropDown.Value, ...
         app.ProcWDropDown.Value, app.ProcDICDropDown.Value, app.ProcGFPDropDown.Value}, ...
        {'r', 'g', 'b', 'k', 'k', 'y'} ...
    );
end

